---
- name: Verify
  hosts: all
  tasks:
    - name: Check if NGINX is installed
      ansible.builtin.package:
        name: nginx
        state: present
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)

    - name: Check if NGINX service is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
      check_mode: true
      register: service
      failed_when: (service is changed) or (service is failed)

    - name: Check default.conf does not exist
      ansible.builtin.stat:
        path: /etc/nginx/conf.d/default.conf
      check_mode: true
      register: stat_result
      failed_when: stat_result.stat.exists

    - name: Check mock.conf does not exist
      ansible.builtin.stat:
        path: /etc/nginx/conf.d/mock.conf
      check_mode: true
      register: stat_result
      failed_when: stat_result.stat.exists
