---
galaxy_info:
  author: buluma
  description: Ansible role for NGINX
  role_name: nginx
  namespace: buluma  # Ansible Lint requirement
  company: ShadowNet

  license: Apache License, Version 2.0

  min_ansible_version: "2.12"

  platforms:
    - name: Alpine
      versions:
        - all
    - name: Amazon
      versions:
        - all
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: EL
      versions:
        - "7"
        - "8"
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
    - name: opensuse
      versions:
        - all

  galaxy_tags:
    - nginx
    - oss
    - opensource
    - plus
    - web
    - server
    - development
    - install

dependencies: []

collections:
  - ansible.posix
  - community.general
  - community.docker
