---
- name: Verify
  hosts: all
  tasks:
    - name: Check if NGINX is installed
      ansible.builtin.package:
        name: nginx
        state: present
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)

    - name: Check if NGINX service is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
      check_mode: true
      register: service
      failed_when: (service is changed) or (service is failed)

    - name: Verify NGINX is up and running
      ansible.builtin.uri:
        url: http://localhost
        status_code: 200

    - name: Check default.conf exists
      ansible.builtin.stat:
        path: /etc/nginx/conf.d/default.conf
      check_mode: true
      register: stat_result
      failed_when: not stat_result.stat.exists

    - name: Ensure default.conf contains 'location /'
      ansible.builtin.lineinfile:
        path: /etc/nginx/conf.d/default.conf
        line: "    location / {"
        state: present
      check_mode: true
      register: conf
      failed_when: (conf is changed) or (conf is failed)

    - name: Check location_snippet.conf exists
      ansible.builtin.stat:
        path: /etc/nginx/snippets/location_snippet.conf
      check_mode: true
      register: stat_result
      failed_when: not stat_result.stat.exists
