---
- name: Converge
  hosts: nap
  tasks:
    - name: Install NGINX App Protect WAF
      ansible.builtin.include_role:
        name: nginx_app_protect # ansible-role-nginx_app_protect
      vars:
        nginx_app_protect_license:
          certificate: license/nginx-repo.crt
          key: license/nginx-repo.key
        nginx_app_protect_remove_license: false
        nginx_app_protect_waf_install_signatures: true
        nginx_app_protect_waf_install_threat_campaigns: true
        nginx_app_protect_timeoutstartsec: 180
